{% set name = "openapi-schema-pydantic" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openapi-schema-pydantic/openapi-schema-pydantic-{{ version }}.tar.gz
  sha256: 3e22cf58b74a69f752cc7e5f1537f6e44164282db2700cbbcd3bb99ddd065196

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pydantic >=1.8.2

test:
  imports:
    - openapi_schema_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kuimono/openapi-schema-pydantic
  doc_url: https://github.com/kuimono/openapi-schema-pydantic
  dev_url: https://github.com/kuimono/openapi-schema-pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: OpenAPI (v3) specification schema as pydantic class
  description: |
    OpenAPI (v3) specification schema as Pydantic classes. The naming of the classes follows the schema in OpenAPI specification.

extra:
  recipe-maintainers:
    - YYYasin19
