{% set name = "openapi-schema-pydantic" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openapi-schema-pydantic-{{ version }}.tar.gz
  sha256: 3e22cf58b74a69f752cc7e5f1537f6e44164282db2700cbbcd3bb99ddd065196

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pydantic >=1.8.2

test:
  imports:
    - openapi_schema_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kuimono/openapi-schema-pydantic
  summary: OpenAPI (v3) specification schema as pydantic class
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - openapi_schema_pydantic/v3/v3_0_3/license.py
    - openapi_schema_pydantic/v3/v3_1_0/license.py

extra:
  recipe-maintainers:
    - YYYasin19
